{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wazuh.labels" . | nindent 4 }}
data:
  wazuh-realm.json: |-
    {
      "realm": {{ .Values.keycloak.realm | quote }},
      "enabled": true,
      "sslRequired": "external",
      "registrationAllowed": false,
      "loginWithEmailAllowed": true,
      "duplicateEmailsAllowed": false,
      "groups": [
        { "name": "admin" },
        { "name": "security_analytics_full_access" },
        { "name": "security_analytics_read_access" }
      ],
      "clientScopes": [
        {
          "name": "groups",
          "protocol": "openid-connect",
          "attributes": {
            "include.in.token.scope": "true",
            "display.on.consent.screen": "true"
          },
          "protocolMappers": [
            {
              "name": "groups",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-group-membership-mapper",
              "consentRequired": false,
              "config": {
                "full.path": "false",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "claim.name": "groups",
                "userinfo.token.claim": "true"
              }
            }
          ]
        }
      ],
      "clients": [
        {
          "clientId": "wazuh",
          "name": "wazuh",
          "enabled": true,
          "clientAuthenticatorType": "client-secret",
          "secret": {{ .Values.keycloak.clientSecret | quote }},
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": true,
          "serviceAccountsEnabled": false,
          "publicClient": false,
          "frontchannelLogout": true,
          "protocol": "openid-connect",
          "redirectUris": ["https://{{ .Values.ingress.host }}/*"],
          "webOrigins": ["https://{{ .Values.ingress.host }}"],
          "defaultClientScopes": ["groups"],
          "optionalClientScopes": [],
          "protocolMappers": [
            {
              "name": "audience",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-audience-mapper",
              "consentRequired": false,
              "config": {
                "included.client.audience": "wazuh",
                "id.token.claim": "false",
                "access.token.claim": "true"
              }
            },
            {
              "name": "preferred_username",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-usermodel-property-mapper",
              "consentRequired": false,
              "config": {
                "userinfo.token.claim": "true",
                "user.attribute": "username",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "claim.name": "preferred_username",
                "jsonType.label": "String"
              }
            },
            {
              "name": "email",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-usermodel-property-mapper",
              "consentRequired": false,
              "config": {
                "userinfo.token.claim": "true",
                "user.attribute": "email",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "claim.name": "email",
                "jsonType.label": "String"
              }
            }
          ]
        }
      ]
    }
{{- end }}
