{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wazuh.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-username: {{ .Values.keycloak.admin.username | quote }}
  admin-password: {{ .Values.keycloak.admin.password | quote }}
  db-password:    {{ .Values.keycloak.db.password | quote }}
  client-secret:  {{ .Values.keycloak.clientSecret | quote }}
{{- end }}
