apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-manager-master
  namespace: wazuh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-manager
      node-type: master
  serviceName: wazuh-cluster
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: wazuh-manager
        node-type: master
      name: wazuh-manager-master
    spec:   
      containers:
        - name: wazuh-manager
          image: wazuh/wazuh-manager:5.0.0
          env:
            - name: INDEXER_URL
              value: https://wazuh.indexer:9200
            - name: INDEXER_USERNAME 
              value: admin
            - name: INDEXER_PASSWORD
              value: admin
            - name: FILEBEAT_SSL_VERIFICATION_MODE
              value: full
            - name: SSL_CERTIFICATE_AUTHORITIES
              value: /etc/ssl/root-ca.pem
            - name: SSL_CERTIFICATE
              value: /etc/ssl/filebeat.pem
            - name: SSL_KEY
              value: /etc/ssl/filebeat.key
            - name: API_USERNAME
              value: wazuh-wui
            - name: API_PASSWORD
              value: MyS3cr37P450r.*-  
          resources:
            requests:
              cpu: 200m
              memory: 1024Mi
            limits:
              cpu: 500m
              memory: 2048Mi
          volumeMounts:
            - name: wazuh
              mountPath: /var/ossec/
            - name: filebeat_etc
              mountPath: /etc/filebeat
            - name: filebeat_var
              mountPath: /var/lib/filebeat
            - name: config
              mountPath: /wazuh-config-mount/etc/ossec.conf
              subPath: ossec.conf
              readOnly: true
            - name: wazuh-manager-master
              subPath: etc
              mountPath: /var/ossec/etc  
            - name: wazuh-sslmanager
              mountPath: /var/ossec/data/etc/sslmanager.key
              subPath: sslmanager.key
              readOnly: true
            - name: wazuh-sslmanager
              mountPath: /var/ossec/data/etc/sslmanager.cert
              subPath: sslmanager.cert
              readOnly: true
            - name: wazuh-sslmanager
              mountPath: /var/ossec/data/etc/rootCA.key
              subPath: rootCA.key
              readOnly: true
            - name: wazuh-sslmanager
              mountPath: /var/ossec/data/etc/rootCA.pem
              subPath: rootCA.pem
              readOnly: true            
          ports:
            - containerPort: 1515
              name: registration
            - containerPort: 1516
              name: cluster
            - containerPort: 55000
              name: api
      volumes:
      - name: wazuh-manager-master
        persistentVolumeClaim:
          claimName: wazuh-manager-master
      - name: config
        configMap:
          name: wazuh-manager-master-conf
      - name: wazuh-sslmanager
        secret:
          secretName: wazuh-sslmanager
  volumeClaimTemplates:
    - metadata:
        name: wazuh
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi

    - metadata:
        name: filebeat
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
