apiVersion: v1
kind: Secret
metadata:
  name: wazuh-agent-enroll
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wazuh.labels" . | nindent 4 }}
type: Opaque
stringData:
  enroll-token: {{ .Values.credentials.agentRegistration | quote }}
