apiVersion: v1
kind: Service
metadata:
  name: wazuh-indexer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wazuh.labels" . | nindent 4 }}
    app: wazuh-indexer
    node-type: index
spec:
  type: ClusterIP
  selector:
    app: wazuh-indexer
    node-type: index
  ports:
    - name: opensearch
      port: 9200
      targetPort: 9200
